using Content.Shared.CrateTimer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.CrateTimer.UI; // Добавили .UI

[GenerateTypedNameReferences]
public sealed partial class TimerCrateWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnActivatePressed;

    public TimerCrateWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Если MinSize в XAML все еще выдает ошибку, раскомментируй строку ниже:
        // SetSize = (250, 150);

        ActivateButton.OnPressed += _ => OnActivatePressed?.Invoke();
    }

    public void UpdateState(TimerCrateBoundUserInterfaceState state)
    {
        var remaining = state.NextEventTime - _timing.CurTime;
        if (remaining < TimeSpan.Zero) remaining = TimeSpan.Zero;

        StatusLabel.Text = $"Статус: {state.CurrentState}";
        TimeLabel.Text = $"Осталось: {remaining:mm\\:ss}";

        var progress = 1.0f - (float) (remaining.TotalSeconds / state.TotalDuration.TotalSeconds);
        TimerBar.Value = Math.Clamp(progress, 0f, 1f);

        ActivateButton.Disabled = state.CurrentState != TimerCrateState.Idle;
    }
}
