using Content.Shared._Exodus.Crucible;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.Crucible.UI;

[GenerateTypedNameReferences]
public sealed partial class CrucibleWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    public Action<CrucibleUiButton>? OnAction;
    private CrucibleBoundUserInterfaceState? _state;

    public CrucibleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        StartBtn.OnPressed += _ => OnAction?.Invoke(CrucibleUiButton.Start);
        AbortBtn.OnPressed += _ => OnAction?.Invoke(CrucibleUiButton.Abort);
    }

    public void UpdateState(CrucibleBoundUserInterfaceState state)
    {
        _state = state;
        ItemNameLabel.Text = state.ItemName ?? "Пусто";

        StartBtn.Visible = !state.IsProcessing;
        StartBtn.Disabled = state.ItemName == null || !state.HasPower;
        AbortBtn.Visible = state.IsProcessing;

        PowerStatusLabel.Text = state.HasPower ? "Система активна" : "Критическая ошибка: Нет питания";
        PowerStatusLabel.FontColorOverride = state.HasPower ? Color.FromHex("#4b7f3f") : Color.FromHex("#7f3f3f");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_state == null || !_state.IsProcessing)
        {
            Progress.Value = 0;
            TimeLabel.Text = "00:00";
            return;
        }

        var rem = _state.FinishTime - _timing.CurTime;
        if (rem < TimeSpan.Zero) rem = TimeSpan.Zero;
        TimeLabel.Text = $"{rem:mm\\:ss}";

        if (_state.TotalTime.TotalSeconds > 0)
            Progress.Value = Math.Clamp(1.0f - (float)(rem.TotalSeconds / _state.TotalTime.TotalSeconds), 0, 1);
    }
}
