[chat]
motd = "Проект режима Frontier от SS220! Сервер находится в состоянии открытых бета-тестов\nЗаходите на наш Discord-сервер!\nhttps://discord.gg/ss220\n\nУ нас также присутствует удобная веб-карта для просмотра шаттлов: клик на сервер в лаунчере > вебсайт.\n\nПриятной игры!"
